<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>$(NetRoslyn)</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RunTests.csproj" />
    <ProjectReference Include="..\..\..\Compilers\Test\Core\Microsoft.CodeAnalysis.Test.Utilities.csproj" />
  </ItemGroup>
</Project>
